name: CreateRoadRunnerRelease

on:
  create:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        run: |
          tag_name=${{ github.ref }}
          gh release create $tag_name --notes "Release $tag_name"
