name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name:
      Build on ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ "windows-latest", "macos-latest", "ubuntu-latest" ]
        cpp_standard: [ 20 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
