name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name: Build on ${{ matrix.platform.name }}-python${{ matrix.python_version.version }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos-latest-release
            os_type: macos
            os_name: macos-latest
            arch: x86_64
            build_type: Release
            build_tests: ON
            build_plugins: ON
            build_python: ON
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-macosx_11_7_x86_64.zip"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-macos-latest-release.zip"
          - name: macos-latest-debug
            os_type: macos
            os_name: macos-latest
            arch: x86_64
            build_type: Debug
            build_tests: ON
            build_plugins: ON
            build_python: ON
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-macosx_11_7_x86_64.zip"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-macos-latest-debug.zip"
          - name: ubuntu-latest-release
            os_type: ubuntu
            os_name: ubuntu-latest
            build_type: Release
            build_tests: ON
            build_plugins: ON
            build_python: ON
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm13-ubuntu-gcc10-rel.tar.gz"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-ubuntu-latest-release.zip"
          - name: ubuntu-latest-debug
            os_type: ubuntu
            os_name: ubuntu-latest
            build_type: Debug
            build_tests: ON
            build_plugins: ON
            build_python: ON
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm13-ubuntu-gcc10-rel.tar.gz"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-ubuntu-latest-debug.zip"
          - name: windows-latest-release
            os_type: windows
            os_name: windows-latest
            build_type: Release
            build_tests: ON
            build_plugins: ON
            build_python: ON
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-msvc2022-x64-rel.zip"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-windows-latest-release.zip"
          - name: windows-latest-debug
            os_type: windows
            os_name: windows-latest
            build_type: Debug
            build_tests: ON
            build_plugins: ON
            build_python: OFF
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-msvc2022-x64-dbg.zip"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-windows-latest-debug.zip"
          - name: manylinux2014-release
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Release
            build_tests: ON
            build_plugins: ON
            build_python: OFF
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-manylinux2014.tgz"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-manylinux2014-release.zip"
          - name: manylinux2014-debug
            os_type: manylinux
            os_name: ubuntu-latest
            container_image: quay.io/pypa/manylinux2014_x86_64
            build_type: Debug
            build_tests: ON
            build_plugins: ON
            build_python: OFF
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-manylinux2014.tgz"
            libroadrunner_deps_link: "https://github.com/adelhpour/libroadrunner-deps/releases/download/2.1.1/libroadrunner-deps-manylinux2014-debug.zip"
        python_version:
          - name: py39
            version: "3.9"
          #- name: py310
          #  version: "3.10"
          #- name: py311
          #  version: "3.11"
          #- name: py312
          #  version: "3.12"
    runs-on: ${{ matrix.platform.os_name }}
    container:
      image: ${{ matrix.platform.container_image || '' }}

      https://github:
        com/adelhpour/libroadrunner-deps/releases/download/2:
          1:
            1/libroadrunner-deps-macos-latest-debug:
              zip:

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Set MSVC as the default compiler on Windows
        if: matrix.platform.os_type == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.6.0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install ccache
        shell: bash
        run: |
          echo "checking ${RUNNER_WORKSPACE}"
          echo "checking ${GITHUB_WORKSPACE}"
          echo "checking ${{ runner.workspace }}"
          echo "checking $RUNNER_WORKSPACE"
          
          cd ${RUNNER_WORKSPACE}
          if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
            brew install ccache
          elif [ "${{ matrix.platform.os_type }}" == 'ubuntu' ]; then
            sudo apt-get update
            sudo apt-get install -y ccache
          elif [ "${{ matrix.platform.os_type }}" == 'manylinux' ]; then
            mkdir -p ccache
            cd ccache
            curl -L https://github.com/ccache/ccache/releases/download/v4.9.1/ccache-4.9.1.tar.gz > ccache.tar.gz
            tar -zxf ccache.tar.gz
            rm ccache.tar.gz
            mkdir -p build-ccache
            mkdir -p install-ccache
            cd build-ccache
            cmake -DCMAKE_INSTALL_PREFIX="$RUNNER_WORKSPACE/ccache/install-ccache" -DCMAKE_BUILD_TYPE=Release ../ccache-4.9.1
            cmake --build . --target install
            echo "$RUNNER_WORKSPACE/ccache/install-ccache/bin" >> $GITHUB_PATH
          fi

      - name: Prepare ccache timestamp on non-Windows platforms
        if: matrix.platform.os_type != 'windows'
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: Set ccache cache directory on non-Windows
        if: matrix.platform.os_type != 'windows'
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          echo "CCACHE_DIR=${RUNNER_WORKSPACE}/.ccache" >> "${GITHUB_ENV}"
          echo "COMPILER_LAUNCHER=ccache" >> "${GITHUB_ENV}"

      - name: Cache ccache files on non-Windows
        if: matrix.platform.os_type != 'windows'
        uses: actions/cache@v3
        with:
          path: ${RUNNER_WORKSPACE}/.ccache
          key:
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp
            }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
            ${{ runner.os }}-

      - name: Setup Python for non-manylinux platforms
        if: matrix.platform.build_python == 'ON' && matrix.platform.os_type != 'manylinux'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.version }}

      - name: Setup Python for manylinux platforms
        if: matrix.platform.build_python == 'ON' && matrix.platform.os_type == 'manylinux'
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          yum install gcc openssl-devel bzip2-devel libffi-devel -y
          mkdir -p python${{ matrix.python_version.version }}
          cd python${{ matrix.python_version.version }}
          curl -L https://www.python.org/ftp/python/${{ matrix.python_version.version }}.0/Python-${{ matrix.python_version.version }}.0.tgz > python.tgz
          tar -zxf python.tgz
          rm python.tgz
          cd Python-${{ matrix.python_version.version }}.0
          mkdir -p install-python
          ./configure --enable-optimizations --prefix=${RUNNER_WORKSPACE}/python${{ matrix.python_version.version }}/install-python
          make install
          echo "${RUNNER_WORKSPACE}/python${{ matrix.python_version.version }}/install-python/bin" >> $GITHUB_PATH
          echo "export PATH=${RUNNER_WORKSPACE}/python${{ matrix.python_version.version }}/install-python/bin:$PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        if: matrix.platform.build_python == 'ON'
        shell: bash
        run: |
          if [ "${{ matrix.platform.os_type }}" == 'windows' ]; then
            python -m pip install numpy
          else
            python${{ matrix.python_version.version }} -m pip install numpy
          fi

      - name: Install swig
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          # running against the latest version of swig fails, os we build version 4.0.2
          if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
            brew install pcre pcre2
            mkdir -p ${RUNNER_WORKSPACE}/swig
            cd swig
            curl -L https://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz > swig.tar.gz
            tar -zxf swig.tar.gz -C ${{ runner.workspace }}/swig --strip-components=1
            rm swig.tar.gz
            mkdir -p build-swig
            mkdir -p install-swig
            ./configure --prefix=${RUNNER_WORKSPACE}/swig/install-swig
            make
            make install
            echo SWIG_DIR="-DSWIG_EXECUTABLE=${RUNNER_WORKSPACE}/swig/install-swig/bin/swig" >> "${GITHUB_ENV}"
          elif [ "${{ matrix.platform.os_type }}" == 'windows' ]; then
            mkdir -p swig
            cd swig
            curl -L https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip/download > swig.zip
            unzip -q swig.zip -d install-swig
            rm swig.zip
            echo SWIG_DIR="-DSWIG_EXECUTABLE=${RUNNER_WORKSPACE}/swig/install-swig/swigwin-4.0.2/" >> $GITHUB_PATH
          elif [ "${{ matrix.platform.os_type }}" == 'manylinux' ]; then
            yum install -y pcre-devel
            mkdir -p swig
            cd swig
            curl -L https://sourceforge.net/projects/swig/files/swig/swig-4.0.2/swig-4.0.2.tar.gz/download > swig.tar.gz
            tar -zxf swig.tar.gz
            rm swig.tar.gz
            mkdir -p install-swig
            cd swig-4.0.2/
            ./configure --disable-dependency-tracking --prefix=${RUNNER_WORKSPACE}/swig/install-swig
            make
            make install
            echo SWIG_DIR="-DSWIG_EXECUTABLE=${RUNNER_WORKSPACE}/swig/install-swig/bin/swig" >> $GITHUB_PATH
          fi

      - name: Download libRoadRunner dependencies binaries
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          curl -L "${{ matrix.platform.libroadrunner_deps_link }}"
          echo "a) displaying the contents of the directory"
          ls
          unzip -q libroadrunner-deps-${{ matrix.platform.name }}.zip
          echo "b) displaying the contents of the directory"
          ls
          rm libroadrunner-deps-${{ matrix.platform.name }}.zip
          echo "c) displaying the contents of the directory"
          ls ./libroadrunner-deps-${{ matrix.platform.name }}
          echo LIBROADRUNNER_DEPENDENCIES_DIR="-DRR_DEPENDENCIES_INSTALL_PREFIX=${RUNNER_WORKSPACE}/libroadrunner-deps-${{ matrix.platform.name }}" >> "${GITHUB_ENV}"

      - name: Download LLVM binaries
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}
          mkdir -p llvm-binaries
          cd llvm-binaries
          mkdir -p llvm
          if [ "${{ matrix.platform.os_type }}" == 'macos' ]; then
            curl -L "${{ matrix.platform.llvm_link }}" > llvm.zip
            unzip -q llvm.zip -d llvm
            rm llvm.zip
            echo LLVM_DIR="-DLLVM_INSTALL_PREFIX=${RUNNER_WORKSPACE}/llvm-binaries/llvm" >> "${GITHUB_ENV}"
          elif [ "${{ matrix.platform.os_type }}" == 'ubuntu' ]; then
            curl -L "${{ matrix.platform.llvm_link }}" > llvm.tar.gz
            tar -zxf llvm.tar.gz -C llvm --strip-components=1
            rm llvm.tar.gz
            echo LLVM_DIR="-DLLVM_INSTALL_PREFIX=${RUNNER_WORKSPACE}/llvm-binaries/llvm" >> "${GITHUB_ENV}"
          elif [ "${{ matrix.platform.os_type }}" == 'windows' ]; then
            curl -L "${{ matrix.platform.llvm_link }}" > llvm.zip
            unzip -q llvm.zip -d llvm
            rm llvm.zip
            if [ "${{ matrix.platform.build_type }}" == 'Release' ]; then
              echo LLVM_DIR="-DLLVM_INSTALL_PREFIX=${RUNNER_WORKSPACE}\llvm-binaries\llvm\llvm-13.x-msvc2022-x64-rel" >> "${GITHUB_ENV}"
            else
              echo LLVM_DIR="-DLLVM_INSTALL_PREFIX=${RUNNER_WORKSPACE}\llvm-binaries\llvm" >> "${GITHUB_ENV}"
            fi
          elif [ "${{ matrix.platform.os_type }}" == 'manylinux' ]; then
            curl -L "${{ matrix.platform.llvm_link }}" > llvm.x.tar
            tar -zxf llvm.x.tar -C llvm --strip-components=1
            rm llvm.x.tar
            echo LLVM_DIR="-DLLVM_INSTALL_PREFIX=${RUNNER_WORKSPACE}/llvm-binaries/llvm" >> "${GITHUB_ENV}"
          fi

      - name: Create build directory
        shell: bash
        run: mkdir -p ${RUNNER_WORKSPACE}/build-roadrunner

      - name: Configure CMake for RoadRunner
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-roadrunner
          cmake $GITHUB_WORKSPACE \
          -G "Ninja" \
          -DCMAKE_BUILD_TYPE=${{ matrix.platform.build_type }} \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.platform.arch }} \
          -DCMAKE_C_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          -DCMAKE_CXX_COMPILER_LAUNCHER=${COMPILER_LAUNCHER} \
          ${LIBROADRUNNER_DEPENDENCIES_DIR} \
          ${LLVM_DIR} \
          ${SWIG_DIR} \
          -DBUILD_PYTHON=${{ matrix.platform.build_python }} \
          -DBUILD_TESTS=${{ matrix.platform.build_tests }} \
          -DBUILD_RR_PLUGINS=${{ matrix.platform.build_plugins }} \
          -DCMAKE_INSTALL_PREFIX="${RUNNER_WORKSPACE}/install-roadrunner"

      - name: Build and Install RoadRunner
        shell: bash
        run: |
          cd ${RUNNER_WORKSPACE}/build-roadrunner
          cmake --build . --target install --config ${{ matrix.platform.build_type }}
