name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    name:
      Build on ${{ matrix.os.name }} - ${{ matrix.build_type.name }} - Python${{ matrix.python_version.version }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macos-latest-release
            os_name: macos-latest
            build_type: Release
            llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-macosx_11_7_x86_64.zip"
        python_version:
          - name: py310
            version: 3.10
    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version.version }}

      - name: Install Python dependencies
        run: pip${{ matrix.python_version.version }} install numpy

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
