name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build_type: [ Release, Debug ]

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download llvm binaries
        shell: bash
        run: |
          curl -L 'https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-macosx_11_7_x86_64.zip' > llvm.zip
          unzip llvm.zip
          mv llvm-13.x-macosx_11_7_x86_64 llvm
