name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ "ubuntu-latest", "macos-latest", "windows-latest" ]

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Download llvm binaries
        shell: bash
        run: |
          curl -L ${{ matrix.os.llvm_link }} > llvm.zip
          unzip llvm.zip
          ls llvm

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
