name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    strategy:
      fail-fast: false
      matrix:
        platform: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
