name: BuildRoadRunner

on:
  push:
    branches-ignore:
      - '*'

jobs:
  build_on_OSs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [{ name: ubuntu-latest, llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm13-ubuntu-gcc10-rel.tar.gz"}, \
             { name: macos-latest, llvm_link: "https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-macosx_11_7_x86_64.zip"}, \
             { name: windows-latest, llvm_link: " https://github.com/sys-bio/llvm-13.x/releases/download/llvmorg-13.0.0/llvm-13.x-msvc2022-x64-${{ matrix.build_type.llvm_link_expression }}.zip"}]
        build_type: [ { name: "Release", llvm_link_expression: "rel"} , { name: "Debug", llvm_link_expression: "dbg" } ]

    steps:
      - name: Checkout RoadRunner
        uses: actions/checkout@v3

      - name: Download llvm binaries
        shell: bash
        run: |
          curl -L ${{ matrix.os.llvm_link }} > llvm.zip
          unzip llvm.zip
          ls llvm

      - name: Create build directory
        run: mkdir -p ${{ runner.workspace }}/build-roadrunner

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
